language : java
script :
    - cd core
    - mvn install
    - cd ../examples
    - wget https://packagecloud.io/PFGimenez/Kraken/packages/java/pfg.graphic/graphic-toolbox-1.3-SNAPSHOT.jar
    - ant
    - cd ../core
jdk : oraclejdk8
cache :
    directories : "$HOME/.m2"
deploy:
  provider: script
  script: "cp ../.travis.settings.xml $HOME/.m2/settings.xml && mvn jar:jar deploy:deploy || :"
  skip_cleanup: true
  on:
    all_branches: true
